version: "3.3"
services:
  discord_bot:
    image: logging_bot:latest
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_CHANNEL=${DISCORD_TOKEN}
      - BLACKLIST_CHANNELS=${BLACKLIST_CHANNELS}
    restart: unless-stopped